Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [12]:
import numpy as np
N = 10
a = np.array(range(N))
x = a[::-1]

print(x, type(x))

[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [61]:
N = 12

my_matrix = np.diag(np.arange(N, -1, -1), k=0)
sum_of_diag_elements = 0
counter = -1
for i in my_matrix:
    counter +=1
    sum_of_diag_elements += i[counter]

print(my_matrix)
  
print(sum_of_diag_elements)



[[12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]
78


Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [4]:
import numpy as np
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбцы - количество покупок категорий товаров этим пользователем.

На сайт заходит новый посетитель next_user_stats

Найдите самого похожего пользователя в таблице user_stats. 

Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [30]:
import numpy as np
from numpy import linalg

#в матрице данные по всем пользователям
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0]) #это новый пользователь


cosinus_list = []
for user_description in users_stats: #создаем цикл для сравнения нового пользователя со всеми предыдущими из матрицы
    a = user_description
    b = next_user_stats 
    
    aLength = np.linalg.norm( a ) #считаем длины векторов 
    bLength = np.linalg.norm( b )
    
    cosinus_lookalike = np.dot( a, b ) / ( aLength * bLength ) #считаем векторное сходство нового пользователя с одним из старых
    
    cosinus_list.append(cosinus_lookalike) # добавляем результат в список
    
best_result = max(cosinus_list) #находим максимальное значение в списке результатов

index_of_best_result = cosinus_list.index(best_result) #находим, какой индекс у этого значения в списке результатов

best_result_user_data_in_users_stats = users_stats[index_of_best_result] #по этому индексу находим пользователя с соответствующими данными в матрице

print(best_result_user_data_in_users_stats)



[0 1 1 0 0 0]
